# Generated by Django 5.2.5 on 2025-08-27 01:19

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140, validators=[post.models.validate_no_bad_words]),
        ),
    ]
