# Generated by Django 5.2.5 on 2025-08-26 23:40

import useraccount.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_remove_useraccount_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_color',
            field=useraccount.models.RGBcolorField(max_length=6, null=True),
        ),
    ]
