# Generated by Django 5.2.5 on 2025-08-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_useraccount_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
