# Generated by Django 5.2.5 on 2025-08-28 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profilepage', '0002_auto_20211013_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='user_account',
        ),
        migrations.AddField(
            model_name='profilepage',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
